/**
 * Script to display the last modified date for each page
 * Reads from last-modified.json which is generated by generate-last-modified.js
 */
window.addEventListener('DOMContentLoaded', () => {
  updateLastModifiedDate();
});

async function updateLastModifiedDate() {
  // Check if we're on one of the main pages that should show the last updated date
  const updateElement = document.getElementById('update-date');
  if (!updateElement) return;
  
  try {
    // Determine which section we're in based on the URL
    let currentSection = 'root'; // Default to root
    const path = window.location.pathname;
    
    if (path.includes('/projects/')) {
      currentSection = 'projects';
    } else if (path.includes('/playground/')) {
      currentSection = 'playground';
    } else if (path.includes('/cv/')) {
      currentSection = 'cv';
    }
    
    // Try to fetch the last-modified.json file
    let lastModified;
    
    try {
      const response = await fetch('/last-modified.json');
      if (!response.ok) throw new Error('Failed to fetch last-modified.json');
      
      const data = await response.json();
      lastModified = data[currentSection];
      
      if (!lastModified) {
        throw new Error(`No last modified date found for section: ${currentSection}`);
      }
      
      // Format the date
      const date = new Date(lastModified);
      updateElement.textContent = date.toLocaleDateString();
    } catch (fetchError) {
      console.warn('Could not load last-modified.json:', fetchError);
      
      // Fallback: try to get the current file's modified date
      try {
        // Get the current HTML file name
        const pathArray = window.location.pathname.split('/');
        const currentFile = pathArray[pathArray.length - 1] || 'index.html';
        
        const fileInfo = await window.fs.stat(currentFile);
        const date = new Date(fileInfo.mtime);
        updateElement.textContent = date.toLocaleDateString();
      } catch (fileError) {
        // If all else fails, use the current date
        const today = new Date().toLocaleDateString();
        updateElement.textContent = today;
        console.warn('Using current date as fallback:', fileError);
      }
    }
  } catch (error) {
    console.error('Error getting last modified date:', error);
    // Set to "Unknown" if we encounter an error
    updateElement.textContent = 'Unknown';
  }
}